# Generated by Django 3.2.4 on 2021-06-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0002_alter_article_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
    ]
