# Generated by Django 3.2.4 on 2021-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0007_auto_20210703_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='childrens',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
