# Generated by Django 3.2.4 on 2021-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0008_auto_20210703_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='childrens',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
