# Generated by Django 3.2.4 on 2021-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0012_alter_article_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='childrens',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
