# Generated by Django 3.2.4 on 2021-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0013_auto_20210726_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='childrens',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_name',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
