# Generated by Django 3.2.4 on 2021-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amcarservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=2)),
                ('position', models.CharField(max_length=130)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
